<a href="https://colab.research.google.com/github/Dilajohn/Advanced-python-topics/blob/main/data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd

pd.DataFrame({'yes' :[50, 21], 'No' :[131, 2]})

   yes   No
0   50  131
1   21    2

In [ ]:
pd.DataFrame({'Bob' : [' I liked it', 'It was awful'] , 'Sue' :['pretty good', 'Bland']})

            Bob          Sue
0    I liked it  pretty good
1  It was awful        Bland

In [ ]:
pd.DataFrame({'Bob' :[' I liked it', 'It was awful'] , 'Sue' :['pretty good', 'Bland']}, index=['Product A', 'Product B'])

                    Bob          Sue
Product A    I liked it  pretty good
Product B  It was awful        Bland

In [ ]:
# series
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
pd.Series([30 , 35, 40], index = ['2015 Sales', '2016 Sales', '2017 Sales'], name = 'product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: product A, dtype: int64

In [ ]:
#Reading data files(.csv files)
wines_reviews = pd.read_csv("/winemag-data-130k-v2.json")